# Generated by Django 6.0.4 on 2026-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
