# Generated by Django 6.0.4 on 2026-04-24 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_key",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
