# Generated by Django 6.0.4 on 2026-04-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_session_key"),
        ("posts", "0005_repost_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pinned_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="posts.post",
            ),
        ),
    ]
