# Generated by Django 6.0.4 on 2026-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("like", "Like"),
                    ("comment_reply", "Comment Reply"),
                ],
                max_length=20,
            ),
        ),
    ]
