# Generated by Django 6.0.4 on 2026-04-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_gif_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="repost_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposts",
                to="posts.post",
            ),
        ),
    ]
